### ISSUE TITLE
zuoblog init 后dist/blog下无资源

### ISSUE THREAD

**Issue by Jankos-Lee** [zuoxiaobai/zuo11.com#3]
下载任意一个tag然后 init 出来的资源dist/blog文件夹为空；
GitError: fatal: not a git repository (or any of the parent directories): .git
要在哪儿配置git仓库吗？

**Comment by dev-zuo** [comment]
感谢反馈，目录必须是 git 管理才行。运行 git init 后再试就可以了。
这是个 bug ，有强依赖，目录必须是由 git 管理，下个小版本我修复下
